agenda_unidadatencion:
    resource: "@AgendaBundle/Resources/config/routing/unidadatencion.yml"
    prefix:   /unidadatencion

agenda_medico:
    resource: "@AgendaBundle/Resources/config/routing/medico.yml"
    prefix:   /medico

agenda_homepage:
    path:     /hello/{name}
    defaults: { _controller: AgendaBundle:Default:index }
