usuario_usuario:
    resource: "@UsuarioBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

usuario_registrar_medico:
    path:     /register/medico/{medicoId}
    defaults: { _controller: FOSUserBundle:Registration:registrarMedico }