hist_clinica_homepage:
    path:     /hello/{name}
    defaults: { _controller: HistClinicaBundle:Default:index }
    
HistClinicaBundle_grupo:
    resource: "@HistClinicaBundle/Resources/config/routing/grupo.yml"
    prefix: /grupo

HistClinicaBundle_convenio:
        resource: "@HistClinicaBundle/Resources/config/routing/convenio.yml"
        prefix:   /convenio

HistClinicaBundle_pregunta:
        resource: "@HistClinicaBundle/Resources/config/routing/pregunta.yml"
        prefix:   /pregunta

HistClinicaBundle_procedimiento:
        resource: "@HistClinicaBundle/Resources/config/routing/procedimiento.yml"
        prefix:   /procedimiento
        
HistClinicaBundle_historiaClinica:
        resource: "@HistClinicaBundle/Resources/config/routing/historiaClinica.yml"
        prefix: /historiaClinica
        
HistClinicaBundle_tipoPregunta:
        resource: "@HistClinicaBundle/Resources/config/routing/tipopregunta.yml"
        prefix:   /tipoPregunta
        
HistClinicaBundle_opcionrespuesta:
        resource: "@HistClinicaBundle/Resources/config/routing/opcionrespuesta.yml"
        prefix:   /opcionRespuesta

HistClinicaBundle_paciente:
        resource: "@HistClinicaBundle/Resources/config/routing/paciente.yml"
        prefix:   /paciente

HistClinicaBundle_costoProcedimiento:
        resource: "@HistClinicaBundle/Resources/config/routing/costoprocedimiento.yml"
        prefix:   /costoProcedimiento

HistClinicaBundle_sugerencia:
        resource: "@HistClinicaBundle/Resources/config/routing/sugerencia.yml"
        prefix:   /sugerencia

HistClinicaBundle_preguntaopcion:
        resource: "@HistClinicaBundle/Resources/config/routing/preguntaopcion.yml"
        prefix:   /preguntaopcion

HistClinicaBundle_atencion:
        resource: "@HistClinicaBundle/Resources/config/routing/atencion.yml"
        prefix:   /atencion