<?php

namespace SmartApps\ContableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReciboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReciboRepository extends EntityRepository
{
}
