<?php

namespace SmartApps\HistClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtencionRepository extends EntityRepository
{
    public function findAtencionPorHistoria($historiaId){
        $em =$this->getEntityManager();
        $consulta=$em->createQuery('SELECT a FROM HistClinicaBundle:Atencion a WHERE a.historiaClinica = '.$historiaId);
        return $consulta->getResult();
    }
}
