<?php

namespace SmartApps\HistClinicaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticoDienteRepository extends EntityRepository {

    public function findDiagnosticoPorHistoria($historiaId) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT d FROM HistClinicaBundle:DiagnosticoDiente d JOIN d.itemOdontograma i'
                . ' WHERE d.historiaClinica = :historiaId '
                . 'ORDER BY i.noCuadrante, i.noDiente, i.noFila');
        $consulta->setParameter('historiaId', $historiaId);
        return $consulta->getResult();
    }

    public function findDiagnosticoPorUbicacion($historiaId, $cuadrante, $numero, $fila, $ubicacion) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT d FROM HistClinicaBundle:DiagnosticoDiente d JOIN d.itemOdontograma i '
                . 'WHERE d.historiaClinica = :historiaId '
                . 'AND i.noCuadrante = :noCuadrante '
                . 'AND i.noDiente = :noDiente '
                . 'AND i.noFila = :noFila '
                . 'AND d.ubicacion = :ubicacion');
        $consulta->setParameter('historiaId', $historiaId);
        $consulta->setParameter('noCuadrante', $cuadrante);
        $consulta->setParameter('noDiente', $numero);
        $consulta->setParameter('noFila', $fila);
        $consulta->setParameter('ubicacion', $ubicacion);
        return $consulta->getOneOrNullResult();
    }

}
