unidadatencion:
    path:     /
    defaults: { _controller: "AgendaBundle:UnidadAtencion:index" }

unidadatencion_show:
    path:     /{id}/show
    defaults: { _controller: "AgendaBundle:UnidadAtencion:show" }

unidadatencion_new:
    path:     /new
    defaults: { _controller: "AgendaBundle:UnidadAtencion:new" }

unidadatencion_create:
    path:     /create
    defaults: { _controller: "AgendaBundle:UnidadAtencion:create" }
    requirements: { _method: post }

unidadatencion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AgendaBundle:UnidadAtencion:edit" }

unidadatencion_update:
    path:     /{id}/update
    defaults: { _controller: "AgendaBundle:UnidadAtencion:update" }
    requirements: { _method: post|put }

unidadatencion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AgendaBundle:UnidadAtencion:delete" }

unidadatencion_search:
    path:     /search
    defaults: { _controller: "AgendaBundle:UnidadAtencion:search" }
