<?php

namespace SmartApps\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoRepository extends EntityRepository
{
    public function findMedicoPorUsuario($usuarioId){
        $em =$this->getEntityManager();
        $consulta=$em->createQuery('SELECT m FROM AgendaBundle:Medico m WHERE m.usuario = '.$usuarioId);
        return $consulta->getOneOrNullResult();
    }
    public function queryTodosLosMedicos(){
        $em=  $this->getEntityManager();
        $consulta=$em->createQuery("SELECT m FROM AgendaBundle:Medico m");
        return $consulta;
    }
    public function queryBuscarMedicos($search){
        $em=  $this->getEntityManager();
        $consulta=$em->createQuery("SELECT m FROM AgendaBundle:Medico m "
                . "WHERE m.nombreCompleto LIKE :search OR m.titulosEspecialidad LIKE :search");
        $consulta->setParameter('search', '%'.$search.'%');
        return $consulta;
    }
}
