<?php

namespace SmartApps\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoRepository extends EntityRepository
{
    public function findMedicoPorUsuario($usuarioId){
        $em =$this->getEntityManager();
        $consulta=$em->createQuery('SELECT m FROM AgendaBundle:Medico m WHERE m.usuario = '.$usuarioId);
        return $consulta->getSingleResult();
    }
}
