<?php

namespace SmartApps\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtencionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadAtencionRepository extends EntityRepository
{
    public function queryTodasLasUnidades(){
        $em=  $this->getEntityManager();
        $consulta=$em->createQuery("SELECT u FROM AgendaBundle:UnidadAtencion u");
        return $consulta;
    }
    public function queryBuscarUnidades($search){
        $em=  $this->getEntityManager();
        $consulta=$em->createQuery("SELECT u FROM AgendaBundle:UnidadAtencion u "
                . "WHERE u.descripcion LIKE :search ");
        $consulta->setParameter('search', '%'.$search.'%');
        return $consulta;
    }
}
