odontograma_new:
    path: /new/{historiaId}/{grupoId}
    defaults: { _controller: "HistClinicaBundle:Odontograma:new" }
    
odontograma_create:
    path: /create
    defaults: { _controller: "HistClinicaBundle:Odontograma:create" }