paciente:
    path:     /
    defaults: { _controller: "HistClinicaBundle:Paciente:index" }

paciente_show:
    path:     /{id}/show
    defaults: { _controller: "HistClinicaBundle:Paciente:show" }

paciente_new:
    path:     /new
    defaults: { _controller: "HistClinicaBundle:Paciente:new" }

paciente_create:
    path:     /create
    defaults: { _controller: "HistClinicaBundle:Paciente:create" }
    requirements: { _method: post }

paciente_edit:
    path:     /{id}/edit
    defaults: { _controller: "HistClinicaBundle:Paciente:edit" }

paciente_update:
    path:     /{id}/update
    defaults: { _controller: "HistClinicaBundle:Paciente:update" }
    requirements: { _method: post|put }

paciente_delete:
    path:     /{id}/delete
    defaults: { _controller: "HistClinicaBundle:Paciente:delete" }
