pregunta:
    path:     /
    defaults: { _controller: "HistClinicaBundle:Pregunta:index" }

pregunta_show:
    path:     /{id}/show
    defaults: { _controller: "HistClinicaBundle:Pregunta:show" }

pregunta_new:
    path:     /new
    defaults: { _controller: "HistClinicaBundle:Pregunta:new" }

pregunta_create:
    path:     /create
    defaults: { _controller: "HistClinicaBundle:Pregunta:create" }
    requirements: { _method: post }

pregunta_edit:
    path:     /{id}/edit
    defaults: { _controller: "HistClinicaBundle:Pregunta:edit" }

pregunta_update:
    path:     /{id}/update
    defaults: { _controller: "HistClinicaBundle:Pregunta:update" }
    requirements: { _method: post|put }

pregunta_delete:
    path:     /{id}/delete
    defaults: { _controller: "HistClinicaBundle:Pregunta:delete" }

pregunta_createfromtemplate:
    path:     /createfromtemplate
    defaults: { _controller: "HistClinicaBundle:Pregunta:createfromtemplate" }
    
pregunta_savefromtemplate:
    path:     /savefromtemplate
    defaults: { _controller: "HistClinicaBundle:Pregunta:savefromtemplate" }
 
pregunta_search:
    path:     /search
    defaults: { _controller: "HistClinicaBundle:Pregunta:search" }