tipopregunta:
    path:     /
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:index" }

tipopregunta_show:
    path:     /{id}/show
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:show" }

tipopregunta_new:
    path:     /new
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:new" }

tipopregunta_create:
    path:     /create
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:create" }
    requirements: { _method: post }

tipopregunta_edit:
    path:     /{id}/edit
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:edit" }

tipopregunta_update:
    path:     /{id}/update
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:update" }
    requirements: { _method: post|put }

tipopregunta_delete:
    path:     /{id}/delete
    defaults: { _controller: "HistClinicaBundle:TipoPregunta:delete" }

